# Generated by Django 6.0.6 on 2026-06-20 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('paper', models.CharField(choices=[('Paper 1', 'Paper 1'), ('Paper 2', 'Paper 2'), ('Paper 3', 'Paper 3'), ('Practical', 'Practical')], max_length=20)),
                ('pdf', models.FileField(upload_to='past_papers/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
