# Generated by Django 6.0.6 on 2026-06-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
